### ISSUE TITLE
Ramas para subir el código

### ISSUE THREAD

**Issue by AndrextA** [mmasias/23-24-eda2#172]
No hay ramas para el código del reto 4 de recursividad y tampoco del BigO

**Comment by mmasias** [comment]
¡Perdón! Pensaba que la había creado: ya la tienes creada. 

Lo de BigO no era formalmente entregable, aunque si quieres inclúyelo en la presente entrega y lo debatimos en clase.

PS: Si está ok, close the issue ;)
